# Generated by Django 5.0.3 on 2024-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='houve_vitimas_reports',
            field=models.CharField(default='Não', max_length=4),
        ),
    ]
