# Generated by Django 5.0.6 on 2024-07-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reports_houve_vitimas_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='sala_reports',
            new_name='local_reports',
        ),
    ]
