# Generated by Django 5.0.6 on 2024-07-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_sala_reports_reports_local_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_planta', models.CharField(max_length=100)),
                ('pais_planta', models.CharField(max_length=100)),
                ('estado_planta', models.CharField(max_length=100)),
                ('cidade_planta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_situacao', models.CharField(max_length=100)),
                ('descricao_situacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=100)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_risco', models.CharField(max_length=100)),
                ('descricao_risco', models.CharField(max_length=255)),
                ('situcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.situacao')),
            ],
        ),
    ]
