# Generated by Django 5.0.6 on 2024-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_planta_situacao_local_risco'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='interno_exerno_local',
            field=models.CharField(default='interno', max_length=100),
            preserve_default=False,
        ),
    ]
