# Generated by Django 5.0.7 on 2024-07-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_situacao_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risco',
            old_name='situcao',
            new_name='situacao',
        ),
    ]
