# Generated by Django 5.0.7 on 2024-07-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_risco_erifica_area_risco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risco',
            old_name='erifica_area_Risco',
            new_name='verifica_area_risco',
        ),
    ]
