# Generated by Django 5.0.7 on 2024-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reports_nivel_danos_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='area_responsavel_reports',
            field=models.CharField(default='HSE', max_length=10),
            preserve_default=False,
        ),
    ]
