# Generated by Django 5.0.7 on 2024-07-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_local_interno_exerno_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.local'),
            preserve_default=False,
        ),
    ]
