# Generated by Django 5.0.6 on 2024-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cost_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=45)),
                ('device_serial_number', models.CharField(max_length=45)),
                ('device_last_use', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('ds_id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'device_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_plant', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_retrieval_date', models.DateField()),
                ('order_delivery_date', models.DateField()),
                ('order_ticket_it', models.CharField(max_length=45)),
                ('order_ticket_user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'order_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_edv', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
