# Generated by Django 5.0.7 on 2024-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_situcao_risco_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='erifica_area_Risco',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='verifica_area_situacao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
